# Generated by Django 4.2.14 on 2024-07-22 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_plane'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='plane',
            name='airline',
            field=models.ForeignKey(default=123456789, on_delete=django.db.models.deletion.CASCADE, related_name='airway', to='flights.airline'),
            preserve_default=False,
        ),
    ]
