# Generated by Django 4.2.14 on 2024-07-22 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_airline_plane_airline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.airline'),
        ),
    ]
