# Generated by Django 4.2.14 on 2024-07-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_plane_airline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plane',
            name='airline',
        ),
        migrations.DeleteModel(
            name='Airline',
        ),
    ]
