# Generated by Django 4.2.14 on 2024-07-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_flight_plane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='plane',
        ),
    ]
