# Generated by Django 4.2.14 on 2024-07-22 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_remove_flight_plane'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='flights.plane'),
            preserve_default=False,
        ),
    ]
