# Generated by Django 4.2.14 on 2024-07-22 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0008_flight_plane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.plane'),
        ),
    ]
