# Generated by Django 4.2.14 on 2024-07-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_airline_remove_plane_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='registration_number',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
